import csv
import tkinter.messagebox as mb
from datetime import datetime

import dateutil
import GIS_Google_pin_util
import GIS_location_util
import IO_csv_util
import IO_files_util
import IO_user_interface_util
import simplekml

# generates .kml file based on CSV of geocoded locations with row format filename,loc type,name,lat,lng
# headers row(s) are NOT expected
# will colorize pins of different files differently, supports up to 300 unique colors (hex values)
# Red – ff0000ff.
# Yellow – ff00ffff.
# Blue – ffff0000.
# Green – ff00ff00.
# Purple – ff800080.
# Orange – ff0080ff.
# Brown – ff336699.
# Pink – ffff00ff.

# def generate_kml_byRecord(window, inputFilename, row, inputGeocodedCsvFile,
# 				 datePresent,
# 				 locationColumnName,
# 				 encodingValue,
# 				 group_var, group_number_var, group_values_entry_var_list, group_label_entry_var_list,
# 				 icon_var_list, specific_icon_var_list,
# 				 name_var_list, scale_var_list, color_var_list, color_style_var_list,
# 				 bold_var_list, italic_var_list,
# 				 description_var_list, description_csv_field_var_list, colorize=True):
#
# 	# Icon selection
#
# 	# if inputIsCoNLL==True:
# 	if datePresent == True:
# 		if date != 'nan' and date != '':
# 			# if dates are present they MUST be converted to Google Earth Pro expected date format yyyy-mm-dd
# 			# get format of your date
# 			# https://stackoverflow.com/questions/44298131/detecting-date-format-and-converting-them-to-mm-dd-yyyy-using-Python
# 			# date options https://i.pinimg.com/736x/25/f7/0d/25f70de25821648c2f268b3d52da6eb8.jpg
#
# 			# https://stackoverflow.com/questions/25341945/check-if-string-has-date-any-format
# 			# %b : Returns the first three characters of the month name. ...
# 			# %B : Returns the full name of the month, e.g. September
# 			# %m : Returns month in 2 digit form 1 to 12
# 			# %d : Returns day of the month, from 1 to 31
# 			# %Y : Returns the year in four-digit format
# 			# %y : Returns the year in two-digit format 18 for 1918
#
# 			# a combinations of formats are admitted, with:
# 			#    year (2 or 4 digits), month, day in numeric format and in various order
# 			#    with month in 3 or full alphabetic format
# 			fmts = ('%Y', '%y', '%Y-%m-%d', '%y-%m-%d', '%Y-%m', '%y-%m',
# 					'%d-%b-%Y', '%d-%b-%y', '%m-%Y', '%m-%y', '%B-%Y', '%B-%y', '%b-%Y', '%b-%y')
# 			for e in date.splitlines():
# 				for fmt in fmts:
# 						break
# 						pass
# 			# years before 1900 cannot be used
# 			# pre 1900 dates may give a problem in Windows: ValueError: format %y requires year >= 1900 on Windows
# 			# https://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900
# 			# There are various ways to alter strftime so that it handles pre-1900 dates
# 			except:
# 				mb.showerror(title='Date error',
# 							 message="There was an error in processing the date '" + date + "'.\n\nThe date format '" + fmt + "' was automatically applied to process the date, where format values are as follows:\n%B or %b   alphabetic month name in full or first 3 characters;\n%m   2-digit month (1 to 12);\n%d   2-digit day of the month (1 to 31);\n%Y   4-digit and %y 2-digit year (1918, 18).\n\nBut... either\n1.   the format automatically applied is incorrect for the date;\n2.   the date is in unrecognized format (e.g., it contains time besides date);\n3.   the date is prior to 1900. The library 'strftime' used here to deal with dates cannot process dates prior to 1900 in Windows.")
#
# 	# Mapping with one group
# 	# we do not want to print the name of the location or the map becomes unreadable
# 	if row[3] != 0 and row[2] != 0:
# 		#	the code breaks in pin_customizer
# 		#	we would need to process inputfile rather inputFilename
# 		pnt = GIS_Google_pin_util.pin_customizer(inputFilename, pnt, index, index_list, locationColumnName,
# 												 group_var, group_number_var, group_values_entry_var_list,
# 												 group_label_entry_var_list,
# 												 icon_var_list, specific_icon_var_list, icon_url,
# 												 name_var_list, scale_var_list, color_var_list,
# 												 color_style_var_list,
# 												 bold_var_list, italic_var_list,
# 												 description_var_list, description_csv_field_var_list,
# 												 j=0, data=data, headers=headers)


# TODO inputFilename is a csv file generated by the NER_extractor; it would contain a date if datePresent
# TODO inputGeocodedCsvFile does not contain a date; so the date field is lost in order to compute dynamic GIS maps
# the list of arguments reflect the order of widgets in the Google_Earth_main GUI
def generate_kml(
    inputFilename,
    inputGeocodedCsvFile,
    datePresent,
    locationColumnName,
    encodingValue,
    group_var,
    group_number_var,
    group_values_entry_var_list,
    group_label_entry_var_list,
    icon_var_list,
    specific_icon_var_list,
    name_var_list,
    scale_var_list,
    color_var_list,
    color_style_var_list,
    bold_var_list,
    italic_var_list,
    description_var_list,
    description_csv_field_var_list,
    colorize=True,
):

    startTime = IO_user_interface_util.timed_alert(
        2000, "GIS kml generator", "Started running KML algorithm at", True, "", True, "", silent=True
    )

    result = IO_files_util.openCSVFile(inputGeocodedCsvFile, "r", encodingValue)
    if result == "":
        return ""

    kmloutputFilename = inputGeocodedCsvFile.replace(".csv", ".kml")
    inputfile = csv.reader(result)
    kml = simplekml.Kml()
    next(inputfile)  # skip header
    index = 0
    j = 0
    index_list, data, headers, locationColumnNumber = GIS_location_util.extract_index(
        inputFilename, inputGeocodedCsvFile, encodingValue, locationColumnName
    )
    # Icon selection
    icon_url = GIS_Google_pin_util.pin_icon_select(icon_var_list[j], specific_icon_var_list[j])

    if len(index_list) == 0:
        return ""
    if group_number_var <= 1:
        nRecords, nColumns = IO_csv_util.GetNumberOf_Records_Columns_inCSVFile(inputGeocodedCsvFile, encodingValue)
        print("Processing geocoded record for kml:", "1" + "/" + str(nRecords) + " header record skipped")
        for row in inputfile:
            index = index + 1
            currRecord = str(index + 1) + "/" + str(nRecords)
            print("Processing geocoded record for kml:", currRecord)
            GGPdateFormat = ""
            # if inputIsCoNLL==True:
            if datePresent:
                date = row[5]
                if date != "nan" and date != "":
                    # if dates are present they MUST be converted to Google Earth Pro expected date format yyyy-mm-dd
                    # get format of your date
                    # https://stackoverflow.com/questions/44298131/detecting-date-format-and-converting-them-to-mm-dd-yyyy-using-Python
                    # date options https://i.pinimg.com/736x/25/f7/0d/25f70de25821648c2f268b3d52da6eb8.jpg

                    # https://stackoverflow.com/questions/25341945/check-if-string-has-date-any-format
                    # %b : Returns the first three characters of the month name. ...
                    # %B : Returns the full name of the month, e.g. September
                    # %m : Returns month in 2 digit form 1 to 12
                    # %d : Returns day of the month, from 1 to 31
                    # %Y : Returns the year in four-digit format
                    # %y : Returns the year in two-digit format 18 for 1918

                    # a combinations of formats are admitted, with:
                    #    year (2 or 4 digits), month, day in numeric format and in various order
                    #    with month in 3 or full alphabetic format
                    fmts = (
                        "%Y",
                        "%y",
                        "%Y-%m-%d",
                        "%y-%m-%d",
                        "%Y-%m",
                        "%y-%m",
                        "%Y-%B-%d",
                        "%y-%B-%d",
                        "%Y-%b-%d",
                        "%y-%b-%d",
                        "%Y-%B",
                        "%y-%B",
                        "%Y-%b",
                        "%y-%b%m-%d-%Y",
                        "%m-%d-%y",
                        "%d-%m-%Y",
                        "%d-%m-%y",
                        "%m-%Y",
                        "%m-%y",
                        "%B-%d-%Y",
                        "%B-%d-%y",
                        "%b-%d-%Y",
                        "%b-%d-%y",
                        "%d-%B-%Y",
                        "%d-%B-%y",
                        "%d-%b-%Y",
                        "%d-%b-%y",
                        "%m-%Y",
                        "%m-%y",
                        "%B-%Y",
                        "%B-%y",
                        "%b-%Y",
                        "%b-%y",
                    )
                    for e in date.splitlines():
                        for fmt in fmts:
                            try:
                                t = datetime.strptime(e, fmt)
                                break
                            except ValueError:
                                pass
                    currentDateFormat = dateutil.parser.parse(date)
                    # years before 1900 cannot be used
                    # pre 1900 dates may give a problem in Windows: ValueError: format %y requires year >= 1900 on Windows
                    # https://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900
                    # There are various ways to alter strftime so that it handles pre-1900 dates
                    try:
                        GGPdateFormat = currentDateFormat.strftime("%Y-%m-%d")
                    except Exception:
                        print(f"Date error: There was an error in processing the date '{date}' with format '{fmt}'.")
                        return ""

            # Mapping with one group
            # we do not want to print the name of the location or the map becomes unreadable
            if row[3] != 0 and row[2] != 0:
                pnt = kml.newpoint(coords=[(row[3], row[2])])  # wants to be read in in lng, lat order
                pnt.style.iconstyle.icon.href = icon_url
                # the code breaks in pin_customizer
                # we would need to process inputfile rather inputFilename
                pnt = GIS_Google_pin_util.pin_customizer(
                    inputFilename,
                    pnt,
                    index,
                    index_list,
                    locationColumnName,
                    sentence="",
                    group_var=0,
                    group_number_var=1,
                    group_values=[""],
                    group_labels=[""],
                    icon_type_list=["Pushpins"],
                    icon_style_list=["red"],
                    icon_url="http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png",
                    name_var_list=[0],
                    scale_var_list=["1"],
                    color_var_list=[0],
                    color_style_var_list=[""],
                    bold_var_list=[1],
                    italic_var_list=[1],
                    description_var_list=[1],
                    description_csv_field_var_list=["Sentence"],
                    j=0,
                    data=data,
                    headers=headers,
                )

                pnt.timespan.begin = GGPdateFormat
                pnt.timespan.end = GGPdateFormat

    # Mapping with multiple groups
    else:
        for j in range(group_number_var):
            values_raw = []
            values_raw_temp = []
            values_row_num = []
            specified_values_raw = []
            specified_values_temp = []
            specified_values = []

            withHeader_var = IO_csv_util.csvFile_has_header(inputFilename)  # check if the file has header
            data, headers = IO_csv_util.get_csv_data(inputFilename, withHeader_var)  # get the data and header
            # get the column name and its column num that we are splitting groups based on
            icon_csv_field_var_name = icon_csv_field_var  # noqa: F821

            for m in range(len(headers)):
                if icon_csv_field_var_name == headers[m]:
                    icon_csv_field_var_name_num = m

            if len(group_values_entry_var_list[j]) == 0:
                for i in range(len(data)):
                    values_raw_temp.append(data[i][icon_csv_field_var_name_num])

                values_raw = values_raw_temp

                for k in range(len(group_values_entry_var_list)):
                    if len(group_values_entry_var_list[k]) != 0:
                        specified_values_raw.append(group_values_entry_var_list[k])
                        specified_values_temp = specified_values_raw[0].split(",")

                        for u in range(len(specified_values_temp)):
                            specified_values_temp[u] = specified_values_temp[u].strip()

                        for w in range(len(specified_values_temp)):
                            specified_values.append(specified_values_temp[w])
                            specified_values_raw.clear()

                duplicates = []
                for s in range(len(values_raw_temp)):
                    for r in range(len(specified_values)):
                        if values_raw_temp[s] == specified_values[r]:
                            duplicates.append(values_raw_temp[s])

                for t in range(len(duplicates)):
                    values_raw.remove(duplicates[t])

                values = values_raw
                new_value = ", ".join(values)
                group_values_entry_var_list[j] = new_value

            else:
                values_raw.append(group_values_entry_var_list[j])
                values = values_raw[0].split(",")
                for u in range(len(values)):
                    values[u] = values[u].strip()
                new_value = ", ".join(values)
                group_values_entry_var_list[j] = new_value

            for n in range(len(data)):
                for a in range(len(values)):
                    if values[a] == data[n][icon_csv_field_var_name_num]:
                        values_row_num.append(n)

            index = 0
            inputfile = csv.reader(open(inputGeocodedCsvFile, encoding=encodingValue, errors="ignore"))
            nRecords, nColumns = IO_csv_util.GetNumberOf_Records_Columns_inCSVFile(inputGeocodedCsvFile, encodingValue)
            for row in inputfile:
                for b in range(len(values_row_num)):
                    if index - 1 == values_row_num[b]:
                        currRecord = str(index - 1) + "/" + str(nRecords)
                        # we do not want to print the name of the location or the map becomes unreadable
                        pnt = kml.newpoint(
                            coords=[(row[locationColumnNumber + 2], row[locationColumnNumber + 1])]
                        )  # wants to be read in in lng, lat order
                        pnt.style.iconstyle.icon.href = icon_url
                        sentence = ""
                        pnt = GIS_Google_pin_util.pin_customizer(
                            inputFilename,
                            pnt,
                            index,
                            index_list,
                            locationColumnName,
                            sentence,
                            group_var,
                            group_values_entry_var_list,
                            group_label_entry_var_list,
                            icon_var_list,
                            specific_icon_var_list,
                            icon_url,
                            name_var_list,
                            scale_var_list,
                            color_var_list,
                            color_style_var_list,
                            description_var_list,
                            description_csv_field_var_list,
                            description_csv_field_var_list,
                            bold_var_list,
                            italic_var_list,
                            group_number_var,
                            j=0,
                        )
                index = index + 1
    IO_user_interface_util.timed_alert(
        2000, "GIS kml generator", "Finished running KML algorithm at", True, "", True, startTime, silent=True
    )
    try:
        kml.save(kmloutputFilename)
    except Exception:
        mb.showwarning(
            title="kml file save failure",
            message="Saving the kml file failed. A typical cause of failure is is bad characters in the input text/csv file(s) (e.g, 'LINE TABULATION' or 'INFORMATION SEPARATOR ONE' characters).\n\nThe GIS KML script will now try to automattically clean the kml file, save it in safe mode, and open the kml file in Google Earth Pro.\n\nIf the file cleaning was successful, the map will display correctly. If not, Google Earth Pro will open exactly on the bad character position. Remove the character and save the file. But, you should really clean the original input txt/csv file.",
        )
        # Save kml regardless of validity. Let the user find any bad characters.
        kml.save(kmloutputFilename, False)
        # Clean out any "LINE TABULATION" and "INFORMATION SEPARATOR ONE" characters from the input (causes error with KML).
        with open(kmloutputFilename, "r+", encoding="utf_8", errors="ignore") as kmlfile:
            content = kmlfile.read()
            content = content.replace("\u000b", "")
            content = content.replace("\u001f", "")
            kmlfile.seek(0)
            kmlfile.write(content)
            kmlfile.truncate()
    return kmloutputFilename
